# MS5.0 Floor Dashboard - AlertManager Configuration (Production Environment)

global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@ms5dashboard.com'
  smtp_auth_username: 'alerts@ms5dashboard.com'
  smtp_auth_password: 'your_app_password'
  smtp_require_tls: true

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 15m
    
    # High priority alerts
    - match:
        severity: high
      receiver: 'high-priority-alerts'
      group_wait: 30s
      repeat_interval: 30m
    
    # Medium priority alerts
    - match:
        severity: medium
      receiver: 'medium-priority-alerts'
      group_wait: 2m
      repeat_interval: 2h
    
    # Low priority alerts
    - match:
        severity: low
      receiver: 'low-priority-alerts'
      group_wait: 5m
      repeat_interval: 6h
    
    # Database alerts
    - match:
        service: database
      receiver: 'database-alerts'
      group_wait: 1m
      repeat_interval: 1h
    
    # Application alerts
    - match:
        service: application
      receiver: 'application-alerts'
      group_wait: 1m
      repeat_interval: 1h
    
    # Infrastructure alerts
    - match:
        service: infrastructure
      receiver: 'infrastructure-alerts'
      group_wait: 1m
      repeat_interval: 1h

receivers:
  # Critical alerts - immediate notification via multiple channels
  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@ms5dashboard.com,ops@ms5dashboard.com,cto@ms5dashboard.com'
        subject: 'CRITICAL ALERT: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt }}
          {{ end }}
        html: |
          <h2>CRITICAL ALERT: {{ .GroupLabels.alertname }}</h2>
          {{ range .Alerts }}
          <p><strong>Alert:</strong> {{ .Annotations.summary }}</p>
          <p><strong>Description:</strong> {{ .Annotations.description }}</p>
          <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
          <p><strong>Service:</strong> {{ .Labels.service }}</p>
          <p><strong>Instance:</strong> {{ .Labels.instance }}</p>
          <p><strong>Time:</strong> {{ .StartsAt }}</p>
          <hr>
          {{ end }}
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#critical-alerts'
        title: 'CRITICAL ALERT: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Service:* {{ .Labels.service }}
          *Instance:* {{ .Labels.instance }}
          *Time:* {{ .StartsAt }}
          {{ end }}
    webhook_configs:
      - url: 'https://your-alerting-service.com/webhook/critical'
        send_resolved: true

  # High priority alerts
  - name: 'high-priority-alerts'
    email_configs:
      - to: 'admin@ms5dashboard.com,ops@ms5dashboard.com'
        subject: 'HIGH PRIORITY ALERT: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt }}
          {{ end }}
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#alerts'
        title: 'HIGH PRIORITY ALERT: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Service:* {{ .Labels.service }}
          *Instance:* {{ .Labels.instance }}
          *Time:* {{ .StartsAt }}
          {{ end }}

  # Medium priority alerts
  - name: 'medium-priority-alerts'
    email_configs:
      - to: 'ops@ms5dashboard.com'
        subject: 'MEDIUM PRIORITY ALERT: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt }}
          {{ end }}
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#alerts'
        title: 'MEDIUM PRIORITY ALERT: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Service:* {{ .Labels.service }}
          *Instance:* {{ .Labels.instance }}
          *Time:* {{ .StartsAt }}
          {{ end }}

  # Low priority alerts
  - name: 'low-priority-alerts'
    email_configs:
      - to: 'ops@ms5dashboard.com'
        subject: 'LOW PRIORITY ALERT: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt }}
          {{ end }}

  # Database specific alerts
  - name: 'database-alerts'
    email_configs:
      - to: 'dba@ms5dashboard.com,ops@ms5dashboard.com'
        subject: 'DATABASE ALERT: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Database: {{ .Labels.database }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt }}
          {{ end }}
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#database-alerts'
        title: 'DATABASE ALERT: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Database:* {{ .Labels.database }}
          *Instance:* {{ .Labels.instance }}
          *Time:* {{ .StartsAt }}
          {{ end }}

  # Application specific alerts
  - name: 'application-alerts'
    email_configs:
      - to: 'devops@ms5dashboard.com,ops@ms5dashboard.com'
        subject: 'APPLICATION ALERT: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt }}
          {{ end }}
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#application-alerts'
        title: 'APPLICATION ALERT: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Service:* {{ .Labels.service }}
          *Instance:* {{ .Labels.instance }}
          *Time:* {{ .StartsAt }}
          {{ end }}

  # Infrastructure specific alerts
  - name: 'infrastructure-alerts'
    email_configs:
      - to: 'infrastructure@ms5dashboard.com,ops@ms5dashboard.com'
        subject: 'INFRASTRUCTURE ALERT: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Component: {{ .Labels.component }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt }}
          {{ end }}
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#infrastructure-alerts'
        title: 'INFRASTRUCTURE ALERT: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Component:* {{ .Labels.component }}
          *Instance:* {{ .Labels.instance }}
          *Time:* {{ .StartsAt }}
          {{ end }}

  # Default webhook receiver
  - name: 'web.hook'
    webhook_configs:
      - url: 'https://your-alerting-service.com/webhook/default'
        send_resolved: true

# Inhibit rules to prevent alert spam
inhibit_rules:
  # Inhibit high priority alerts when critical alerts are firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'high'
    equal: ['alertname', 'instance', 'service']
  
  # Inhibit medium priority alerts when high priority alerts are firing
  - source_match:
      severity: 'high'
    target_match:
      severity: 'medium'
    equal: ['alertname', 'instance', 'service']
  
  # Inhibit low priority alerts when medium priority alerts are firing
  - source_match:
      severity: 'medium'
    target_match:
      severity: 'low'
    equal: ['alertname', 'instance', 'service']
