# MS5.0 Floor Dashboard - Prometheus Configuration (Staging Environment)

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'staging'
    cluster: 'ms5-staging'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # MS5.0 Backend API
  - job_name: 'ms5-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  # Node Exporter (System metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  # MinIO
  - job_name: 'minio'
    static_configs:
      - targets: ['minio-exporter:9290']

  # Celery Worker
  - job_name: 'celery-worker'
    static_configs:
      - targets: ['flower:5555']
    metrics_path: '/metrics'

  # Application specific metrics
  - job_name: 'ms5-production-metrics'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/api/v1/metrics/production'
    scrape_interval: 30s

  - job_name: 'ms5-oee-metrics'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/api/v1/metrics/oee'
    scrape_interval: 60s

  - job_name: 'ms5-andon-metrics'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/api/v1/metrics/andon'
    scrape_interval: 30s
